# Generated by Django 3.0.3 on 2020-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/pics')),
                ('publisher', models.CharField(max_length=200)),
                ('subtitle1', models.CharField(max_length=200)),
                ('subtitle2', models.CharField(max_length=200)),
                ('subtitle3', models.CharField(max_length=300)),
                ('content', models.TextField()),
            ],
        ),
    ]
