# Generated by Django 3.0.3 on 2020-03-20 15:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_no', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='media/%y/%m/%d')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='subtitle3',
        ),
        migrations.AddField(
            model_name='news',
            name='content1',
            field=models.TextField(default=33.66666666666667),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='content2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newsport.Publisher'),
        ),
    ]
