# Generated by Django 3.0.3 on 2020-04-22 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsport', '0004_sports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports',
            name='name',
        ),
        migrations.AddField(
            model_name='sports',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sports',
            name='content1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sports',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sports',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sports',
            name='news_title',
            field=models.CharField(default='खेल', max_length=200),
        ),
        migrations.AddField(
            model_name='sports',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='newsport.Publisher'),
        ),
        migrations.AddField(
            model_name='sports',
            name='subtitle1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sports',
            name='subtitle2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sports',
            name='title',
            field=models.CharField(default=datetime.datetime(2020, 4, 22, 11, 38, 21, 608961, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
