# Generated by Django 3.0.3 on 2020-04-22 11:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsport', '0005_auto_20200422_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sports',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newsport.Publisher'),
        ),
    ]
