# Generated by Django 3.0.3 on 2020-04-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsport', '0006_auto_20200422_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='news_title',
            field=models.CharField(max_length=200),
        ),
    ]
