# Generated by Django 3.0.3 on 2020-04-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsport', '0007_auto_20200422_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports',
            name='news_title',
        ),
    ]
