# Generated by Django 3.0.3 on 2020-04-22 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsport', '0008_remove_sports_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports',
            name='news_title',
            field=models.CharField(default=datetime.datetime(2020, 4, 22, 13, 34, 33, 68734, tzinfo=utc), max_length=60, verbose_name='News title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sports',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newsport.Publisher'),
        ),
    ]
