# Generated by Django 3.0.3 on 2020-04-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsport', '0009_auto_20200422_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sports',
        ),
    ]
